services:
  skimmer:
    container_name: skimmer
    image: mbari/skimmer:latest
    ports:
      - "5000:5000"
    environment:
      IMAGE_CACHE_SIZE_MB: 100
      ROI_CACHE_SIZE_MB: 10000
      CACHE_DIR: "/etc/skimmer_cache"
      APP_HOST: "0.0.0.0"
      APP_PORT: "5000"
      APP_WORKERS: "8"
      BEHOLDER_URL: "https://gehenna.shore.mbari.org/capture"
      BEHOLDER_API_KEY: "foo"
    volumes:
      - skimmer-data:/etc/skimmer_cache

volumes:
  skimmer-data:
